---
- name: Configure MOTD on Cisco IOS
  hosts: routers
  gather_facts: no
  vars:
    MOTD_TEXT: "{{ MOTD_TEXT | default('Authorized users only!') }}"
  tasks:
    - name: Set banner MOTD
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ MOTD_TEXT }}"
        state: present
