---
- name: Show running-config from Cisco IOS device
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Run 'show running-config'
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: showrun_output

    - name: Ensure output directory exists
      ansible.builtin.file:
        path: outputs
        state: directory

    - name: Save running-config to file (unique per device)
      ansible.builtin.copy:
        content: "{{ showrun_output.stdout[0] }}"
        dest: "outputs/showrun_{{ inventory_hostname }}.txt"

    - name: Display summary
      debug:
        msg: "Saved running-config to outputs/showrun_{{ inventory_hostname }}.txt"
